name="sarfraz"
name
type(name)
name[0]
name[2]
name[1]
name[4]
name[5]
name[6]
name[-1]
name[-2]
name[:]
name[1:4]
name[4:6]
name[3:6]
name[5:6]
name[::-1]
name[::2]
name[1::2]
name[2::4]
name[1::5]
dir(name)
name.upper()
name.lower()
name.title()
name.join("jo")
name.join("ashraff")
sar=1,3,4,"robert",True,3+2j
sar
type(sar)
dir(sar)
sar[1]
sar[3]
sar[4]
sar[2]
sar[0]
sar[1]
sar[::1]
sar[::-3]
sar[2::3]
sar.count(2)
sar.count(3)
sar.count(1)
sar.count(4)
sar.index(1)
sar.index(4)
sar.index("robert")
sar.index(True)
sar2=[1,3,4,"robert",True,3+2j]
sar2
type(sar2)
dir(sar2)
sar3=[1,3,4,"robert",True,3+2j]
sar3
type(sar3)
dir(sar3)
list3=[1,2,3,"baroz",True,2+65j]
list3[3]
list[2]
list3[4]
list[::1]
list3[::2]
list3[::-2]
list3[4]
list3[3:4]
list3[1:3]
list3[3][2:]
list3[3][0:2]
list3[3][1:]
list3.append(32+3j)
list3
list3.insert(1,2)

list3.insert(2,3)
list3
list4=[2,3+2j]
list4
type(list4)
list3.append(list4)
list3
#baroz
'''  sarfraaz'''
student={1:"sarfraz",2:"thazhathathra"}
student
type(student)
dir(student)
id(student)
student[1]
student[2]
students={"name":"sarfraz","dob":"3-12-2005","address":"ramapuram"}
students["name"]
students.keys()
students.values()
students.items()
students["age"]
students["age"]=12
students
students["name"]="jhon"
students.get("address")
students
students.update({"name":"jhon mathew","address":"kadungapuram"})
students
